#ifndef __PIT_H__
#define __PIT_H__

#include "Types.h"

#define PIT_FREQUENCY 1193182
#define MSTOCOUNT(ms) (PIT_FREQUENCY / 1000 * (ms))
#define USTOCOUNT(us) (PIT_FREQUENCY / 1000000 * (us))

// Define PIT I/O Ports
#define PIT_COUNTER0_PORT 0x40
#define PIT_COUNTER1_PORT 0x41
#define PIT_COUNTER2_PORT 0x42
#define PIT_MODE_COMMAND_PORT 0x43

// Define PIT Mode
#define PIT_CONTROL_COUNTER0 0x00
#define PIT_CONTROL_COUNTER1 0x40
#define PIT_CONTROL_COUNTER2 0x80
#define PIT_CONTROL_LSBMSBRW 0x30
#define PIT_CONTROL_LATCH 0x00
#define PIT_CONTROL_MODE0 0x00
#define PIT_CONTROL_MODE2 0x04

// Binary or BCD
#define PIT_CONTROL_BINARYCOUNTER 0x00
#define PIT_CONTROL_BCDCOUNTER 0x01

#define PIT_COUNTROL_BINARYCOUNTER 0x00
#define PIT_COUNTROL_BCDCOUNTER 0x01

#define PIT_COUNTER0_ONCE (PIT_CONTROL_COUNTER0 | PIT_CONTROL_MODE0 |\
     PIT_CONTROL_LSBMSBRW | PIT_CONTROL_BINARYCOUNTER)

#define PIT_COUNTER0_PERIODIC (PIT_CONTROL_COUNTER0 | PIT_CONTROL_MODE2 |\
     PIT_CONTROL_LSBMSBRW | PIT_CONTROL_BINARYCOUNTER)

#define PIT_COUNTER0_LATCH (PIT_CONTROL_COUNTER0 | PIT_CONTROL_LATCH)

// Funtion
void kInitializePIT(WORD wCount, BOOL bPeriodic);
WORD kReadCounter0(void);
void kWaitUsingPIT(WORD wCount);

#endif /* __PIT_H__ */